<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AulaVector.Data\AulaVector.Data.csproj" />
    <ProjectReference Include="..\AulaVector.Models\AulaVector.Models.csproj" />
    <ProjectReference Include="..\AulaVector.Utils\AulaVector.Utils.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
